# Generated by Django 4.1.2 on 2022-10-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_img', models.ImageField(blank=True, upload_to='img/')),
                ('RoomCategory', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Hall', 'Hall')], default='Kitchen', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='models/')),
                ('roomcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.roomcategory')),
            ],
        ),
    ]
