# Generated by Django 4.1.2 on 2022-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='room_img',
        ),
        migrations.AddField(
            model_name='room',
            name='room_img',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
