# Generated by Django 4.1.2 on 2022-11-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_multirooms_roomtype_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backsplash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_splash', models.ImageField(blank=True, upload_to='img/backsplash')),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.roomtype')),
            ],
        ),
    ]
