# Generated by Django 4.1.2 on 2022-11-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_backsplash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.ImageField(blank=True, upload_to='img/cabinet')),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.roomtype')),
            ],
        ),
    ]
