# Generated by Django 4.1.2 on 2022-11-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='cabinet',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
