# Generated by Django 4.1.2 on 2022-11-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_sinkfaucet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walls', models.CharField(blank=True, max_length=10)),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.roomtype')),
            ],
        ),
    ]
