# Generated by Django 4.1.2 on 2022-11-16 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0014_door'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countertop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_top', models.ImageField(blank=True, upload_to='img/backsplash')),
                ('countertopuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.roomtype')),
            ],
        ),
    ]
