# Generated by Django 4.1.2 on 2022-11-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colors',
            name='color_user',
        ),
    ]
