# Generated by Django 4.1.2 on 2022-12-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_remove_colors_color_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metal_Colors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(blank=True, max_length=10)),
                ("color_hex", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Vinyl_Colors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(blank=True, max_length=10)),
                ("color_hex", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Wood_Colors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(blank=True, max_length=10)),
                ("color_hex", models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
